[package]
name = "tfg-mapgen"
version = "0.1.0"
authors = ["Lucille Blumire <llblumire@gmail.com>"]

[dependencies]
image = "0.24.6"
rand = "0.8.5"
serde = "1.0.163"
serde_derive = "1.0.163"
toml = "0.7.4"